-- CREATE TABLE IF NOT EXISTS notifications (
--     id SERIAL PRIMARY KEY,
--     user_id INT NOT NULL, -- Store user ID without foreign key constraint
--     message TEXT NOT NULL,
--     created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
-- );