spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false  # Enable service discovery for dynamic routing
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/v1/users/**
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/v3/auth/**
        - id: task-service
          uri: lb://task-service
          predicates:
            - Path=/v1/tasks/**
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/v1/notifications/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:5173"
              - "http://localhost:5173/"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            allowedHeaders:
              - "*"
            allowCredentials: true
  application:
    name: gateway

# eureka:
#   client:
#     service-url:
#       defaultZone: http://discovery-server:8761/eureka/ # Eureka server

server:
  port: 8080