spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  # Enable service discovery for dynamic routing
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:5173"
              - "http://localhost:5173/"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            allowedHeaders:
              - "*"
            allowCredentials: true
  application:
    name: gateway
  zipkin:
    baseUrl: http://zipkin:9411
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1.0
    integration:
      enabled: true
    scheduled:
      enabled: true

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true

logging:
  level:
    root: INFO
    org:
      [springframework.cloud.gateway.route.RouteDefinitionLocator]: INFO
    [org.springframework.cloud.gateway]: INFO
    [org.springframework.cloud.gateway.filter.ReactiveLoadBalancerClientFilter]: INFO


springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /api/v1/auth/api-docs
        name: Auth Service
      - url: /api/v1/tasks/api-docs
        name: Task Service
      - url: /api/v1/notifications/api-docs
        name: Notification Service

# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,loggers,env,mappings
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
    prometheus:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        http.server.requests: true
  tracing:
    sampling:
      probability: 1.0
  prometheus:
    metrics:
      export:
        enabled: true