spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  # Enable service discovery for dynamic routing
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:5173"
              - "http://localhost:5173/"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            allowedHeaders:
              - "*"
            allowCredentials: true
  application:
    name: gateway

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true

logging:
  level:
    root: INFO
    org:
      [springframework.cloud.gateway.route.RouteDefinitionLocator]: INFO
    [org.springframework.cloud.gateway]: INFO
    [org.springframework.cloud.gateway.filter.ReactiveLoadBalancerClientFilter]: INFO


springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /api/v1/auth/api-docs
        name: Auth Service
      - url: /api/v1/tasks/api-docs
        name: Task Service
      - url: /api/v1/notifications/api-docs
        name: Notification Service