spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://${POSTGRES_URL}:5432/${USER_DB}
    username: ${USER_DB}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8081

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true