spring:
  application:
    name: task-service
  datasource:
    url: jdbc:postgresql://${POSTGRES_URL}:5432/${TASK_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate.format_sql: true
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  file:
    name: src/main/resources/script/stage_log.log
  level:
    org:
      hibernate:
        SQL: OFF
        type: OFF
      springframework:
        web: DEBUG
        data: DEBUG
        boot:
          autoconfigure:
            data:
              rest: DEBUG
            orm: DEBUG
        security: DEBUG
    root: INFO
  # Modify pattern to exclude stack traces
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  # Add exception conversion word to omit stack traces
  exception-conversion-word: "%wEx{short}"
  logback:
    rollingpolicy:
      max-history: 7
      max-file-size: 10MB

# Configure exception handling to not include stack traces
server:
  port: 8082
  servlet:
    context-path: /api/v1
  error:
    include-stacktrace: never
    include-message: always
    include-binding-errors: never
    whitelabel:
      enabled: false

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
  instance:
    hostname: ${SERVICE_HOST:localhost}
    non-secure-port: ${SERVICE_PORT:8082}
    prefer-ip-address: true

springdoc:
  api-docs:
    path: /tasks/api-docs
  swagger-ui:
    path: /swagger-ui.html
openapi:
  service:
    title: Task Service API Documentation
    version: 1.0.0
    url: http://localhost:8080 # API Gateway URL