global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'discovery-server'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['discovery-server:8761']

  - job_name: 'api-gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['gateway:8080']

  - job_name: 'auth-service'
    metrics_path: '/api/v1/actuator/prometheus'
    static_configs:
      - targets: ['auth-service:8081']

  - job_name: 'task-service'
    metrics_path: '/api/v1/actuator/prometheus'
    static_configs:
      - targets: ['task-service:8082']

  - job_name: 'notification-service'
    metrics_path: '/api/v1/actuator/prometheus'
    static_configs:
      - targets: ['notification-service:8083']