name: Test

on:
  push:
    branches: [ develop, 'feature/**' ]
  pull_request:
    branches: [ main, develop ]

jobs:
  setup-services:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_MULTIPLE_DATABASES: auth_test,task_test,notification_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
          
      rabbitmq:
        image: rabbitmq:3-management
        ports:
          - 5672:5672
        options: >-
          --health-cmd "rabbitmqctl status"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      
      - name: Maven Dependency Cache
        id: maven-cache
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      
      - name: Install parent POM
        run: mvn -B install -DskipTests
    
    outputs:
      maven-cache-hit: ${{ steps.maven-cache.outputs.cache-hit }}

  test-discovery-server:
    needs: setup-services
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      
      - name: Maven Dependency Cache
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      
      - name: Test Discovery Server
        run: cd discovery-server && mvn -B test
      
      - name: Generate Test Report
        if: always()
        run: cd discovery-server && mvn surefire-report:report-only
      
      - name: Upload Discovery Server Test Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: discovery-server-test-reports
          path: |
            discovery-server/target/site/surefire-report.html
            discovery-server/target/surefire-reports
          if-no-files-found: warn

  test-api-gateway:
    needs: setup-services
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      
      - name: Maven Dependency Cache
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      
      - name: Test API Gateway
        run: cd api-gateway && mvn -B test
      
      - name: Generate Test Report
        if: always()
        run: cd api-gateway && mvn surefire-report:report-only
      
      - name: Upload API Gateway Test Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: api-gateway-test-reports
          path: |
            api-gateway/target/site/surefire-report.html
            api-gateway/target/surefire-reports
          if-no-files-found: warn

  test-auth-service:
    needs: setup-services
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: auth_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      
      - name: Maven Dependency Cache
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      
      - name: Test Auth Service
        run: cd auth-service && mvn -B test
      
      - name: Generate Test Report
        if: always()
        run: cd auth-service && mvn surefire-report:report-only
      
      - name: Upload Auth Service Test Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: auth-service-test-reports
          path: |
            auth-service/target/site/surefire-report.html
            auth-service/target/surefire-reports
          if-no-files-found: warn

  test-task-service:
    needs: setup-services
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: task_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      
      - name: Maven Dependency Cache
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      
      - name: Test Task Service
        run: cd task-service && mvn -B test
      
      - name: Generate Test Report
        if: always()
        run: cd task-service && mvn surefire-report:report-only
      
      - name: Upload Task Service Test Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: task-service-test-reports
          path: |
            task-service/target/site/surefire-report.html
            task-service/target/surefire-reports
          if-no-files-found: warn

  test-notification-service:
    needs: setup-services
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: notification_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
          
      rabbitmq:
        image: rabbitmq:3-management
        ports:
          - 5672:5672
        options: >-
          --health-cmd "rabbitmqctl status"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      
      - name: Maven Dependency Cache
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      
      - name: Test Notification Service
        run: cd notification-service && mvn -B test
      
      - name: Generate Test Report
        if: always()
        run: cd notification-service && mvn surefire-report:report-only
      
      - name: Upload Notification Service Test Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: notification-service-test-reports
          path: |
            notification-service/target/site/surefire-report.html
            notification-service/target/surefire-reports
          if-no-files-found: warn

  aggregate-reports:
    needs: [test-discovery-server, test-api-gateway, test-auth-service, test-task-service, test-notification-service]
    runs-on: ubuntu-latest
    if: always()
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Create Reports Directory
        run: mkdir -p .github/test-reports/html .github/test-reports/xml
      
      - name: Download Discovery Server Reports
        uses: actions/download-artifact@v4
        with:
          name: discovery-server-test-reports
          path: discovery-server-reports
      
      - name: Download API Gateway Reports
        uses: actions/download-artifact@v4
        with:
          name: api-gateway-test-reports
          path: api-gateway-reports
      
      - name: Download Auth Service Reports
        uses: actions/download-artifact@v4
        with:
          name: auth-service-test-reports
          path: auth-service-reports
      
      - name: Download Task Service Reports
        uses: actions/download-artifact@v4
        with:
          name: task-service-test-reports
          path: task-service-reports
      
      - name: Download Notification Service Reports
        uses: actions/download-artifact@v4
        with:
          name: notification-service-test-reports
          path: notification-service-reports
      
      - name: Organize Reports
        run: |
          # HTML reports
          mkdir -p .github/test-reports/html/discovery-server
          mkdir -p .github/test-reports/html/api-gateway
          mkdir -p .github/test-reports/html/auth-service
          mkdir -p .github/test-reports/html/task-service
          mkdir -p .github/test-reports/html/notification-service
          
          # Copy HTML reports
          cp -r discovery-server-reports/site/* .github/test-reports/html/discovery-server/ || true
          cp -r api-gateway-reports/site/* .github/test-reports/html/api-gateway/ || true
          cp -r auth-service-reports/site/* .github/test-reports/html/auth-service/ || true
          cp -r task-service-reports/site/* .github/test-reports/html/task-service/ || true
          cp -r notification-service-reports/site/* .github/test-reports/html/notification-service/ || true
          
          # XML reports
          mkdir -p .github/test-reports/xml/discovery-server
          mkdir -p .github/test-reports/xml/api-gateway
          mkdir -p .github/test-reports/xml/auth-service
          mkdir -p .github/test-reports/xml/task-service
          mkdir -p .github/test-reports/xml/notification-service
          
          # Copy XML reports
          cp -r discovery-server-reports/surefire-reports/* .github/test-reports/xml/discovery-server/ || true
          cp -r api-gateway-reports/surefire-reports/* .github/test-reports/xml/api-gateway/ || true
          cp -r auth-service-reports/surefire-reports/* .github/test-reports/xml/auth-service/ || true
          cp -r task-service-reports/surefire-reports/* .github/test-reports/xml/task-service/ || true
          cp -r notification-service-reports/surefire-reports/* .github/test-reports/xml/notification-service/ || true
      
      - name: List Collected Reports
        run: |
          echo "HTML Reports:"
          find .github/test-reports/html -type f | sort
          echo "XML Reports:"
          find .github/test-reports/xml -type f | sort
      
      - name: Upload Consolidated Test Reports
        uses: actions/upload-artifact@v4
        with:
          name: consolidated-test-reports
          path: .github/test-reports
          if-no-files-found: warn