name: CD Pipeline (Staging)

on:
  push:
    branches: [ develop ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    
    - name: Build with Maven
      run: mvn -B clean package -DskipTests
    
    - name: Build and Push Docker Images
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        
        # Build and push discovery-server
        docker build -t $DOCKER_USERNAME/discovery-server:latest ./discovery-server
        docker push $DOCKER_USERNAME/discovery-server:latest
        
        # Build and push api-gateway
        docker build -t $DOCKER_USERNAME/api-gateway:latest ./api-gateway
        docker push $DOCKER_USERNAME/api-gateway:latest
        
        # Build and push auth-service
        docker build -t $DOCKER_USERNAME/auth-service:latest ./auth-service
        docker push $DOCKER_USERNAME/auth-service:latest
        
        # Build and push task-service
        docker build -t $DOCKER_USERNAME/task-service:latest ./task-service
        docker push $DOCKER_USERNAME/task-service:latest
        
        # Build and push notification-service
        docker build -t $DOCKER_USERNAME/notification-service:latest ./notification-service
        docker push $DOCKER_USERNAME/notification-service:latest
    
    - name: Deploy to staging server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.STAGING_HOST }}
        username: ${{ secrets.STAGING_USERNAME }}
        key: ${{ secrets.STAGING_SSH_KEY }}
        script: |
          cd ~/taskmanagement
          docker-compose down
          docker-compose pull
          docker-compose up -d